/**
 * PDF Report Export via @react-pdf/renderer
 * Renders client-side and optionally uploads to pb.collection('reports')
 */
import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { pdf, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import pb from "../api/pocketbase";
import { useAuthStore } from "../store/useAuthStore";
import type { AnalysisResponse } from "../types";

interface ReportExportProps {
  result: AnalysisResponse;
}

// Minimal PDF styling
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 11, color: "#333" },
  header: { fontSize: 24, fontWeight: "bold", marginBottom: 20, color: "#1E40AF" },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 10, color: "#1E40AF", borderBottom: "1px solid #ccc", paddingBottom: 4 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 5 },
  label: { color: "#666" },
  value: { fontWeight: "bold" },
  card: { padding: 10, border: "1px solid #ddd", marginBottom: 10, borderRadius: 4 },
  cardHeader: { fontSize: 12, fontWeight: "bold", marginBottom: 4, color: "#1E40AF" },
  cardMetric: { fontSize: 10, color: "#059669" },
  scoreBox: { backgroundColor: "#f0fdf4", padding: 15, borderRadius: 4, alignItems: "center", marginBottom: 20 },
  scoreText: { fontSize: 28, fontWeight: "bold", color: "#059669" },
});

// The PDF Document Definition
const ReportDocument = ({ result }: { result: AnalysisResponse }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>FinResilience Pro — Analysis Report</Text>
      
      {/* Health Score Summary */}
      <View style={styles.scoreBox}>
        <Text style={{ fontSize: 14, marginBottom: 5 }}>Financial Health Score</Text>
        <Text style={styles.scoreText}>{result.health_score.score} / 100</Text>
        <Text style={{ fontSize: 12, marginTop: 5, color: "#666" }}>Grade: {result.grade_label}</Text>
      </View>

      {/* Action Plan */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Action Plan (Prioritized)</Text>
        {result.action_cards.map((card) => (
          <View key={card.priority} style={styles.card}>
            <Text style={styles.cardHeader}>
              Priority {card.priority}: {card.action_type}
            </Text>
            <Text style={{ marginBottom: 4 }}>
              Route ₹{card.amount.toLocaleString()} to {card.destination}
            </Text>
            <Text style={{ fontSize: 10, color: "#666", marginBottom: 4 }}>{card.rationale}</Text>
            <Text style={styles.cardMetric}>{card.impact_metric}</Text>
          </View>
        ))}
      </View>

      {/* Health Benchmarks */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Health Benchmarks</Text>
        <View style={styles.row}>
          <Text style={styles.label}>FOIR (Target ≤ 40%):</Text>
          <Text style={styles.value}>{result.health_score.foir_ratio}%</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Savings Rate (Target ≥ 20%):</Text>
          <Text style={styles.value}>{result.health_score.savings_rate}%</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Emergency Buffer (Target ≥ 3 mo):</Text>
          <Text style={styles.value}>{result.health_score.emergency_months} mo</Text>
        </View>
      </View>

      {/* Payoff Schedule Summary */}
      {result.payoff_schedule.schedule.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Debt Payoff Summary</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Debt-Free By:</Text>
            <Text style={styles.value}>Month {result.payoff_schedule.debt_free_month}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Total Interest Saved (Avalanche):</Text>
            <Text style={styles.value}>₹{result.payoff_schedule.total_interest_saved_vs_minimum.toLocaleString()}</Text>
          </View>
        </View>
      )}

      <Text style={{ fontSize: 9, color: "#999", marginTop: 30, textAlign: "center" }}>
        Generated by FinResilience Pro on {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);


export default function ReportExport({ result }: ReportExportProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { user } = useAuthStore();

  const handleExport = async () => {
    setIsGenerating(true);
    try {
      // Generate PDF blob
      const blob = await pdf(<ReportDocument result={result} />).toBlob();
      
      // Optionally save to PocketBase if user exists
      if (user) {
        const formData = new FormData();
        formData.append("user", user.id);
        formData.append("file", blob, `finresilience_report_${Date.now()}.pdf`);
        try {
          await pb.collection("reports").create(formData);
        } catch (err) {
          console.warn("Could not save to reports collection, but download will proceed", err);
        }
      }

      // Trigger client-side download
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `finresilience_plan_${new Date().toISOString().split('T')[0]}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success("Report downloaded successfully");
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate PDF report");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      className="w-full flex items-center justify-center gap-2 py-3 px-6 bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 transition-colors duration-200 font-bold uppercase tracking-wider text-sm disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
      onClick={handleExport}
      disabled={isGenerating}
      aria-busy={isGenerating}
    >
      {isGenerating ? <Loader2 size={18} className="animate-spin" /> : <Download size={18} />}
      {isGenerating ? "Generating PDF..." : "Download Full PDF Report"}
    </button>
  );
}
